### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by miyuan-beipiao** [junfeng-chen/graph_cfd_supervised#2]
In the [gnn_laminar_flow](https://github.com/cfl-minds/gnn_laminar_flow)/network_utils.py / Line 25:
**_updates = tf.math.add(tf.math.unsorted_segment_sum(messages, edges[:, 0], n_nodes), tf.math.unsorted_segment_sum(
messages, edges[:, 1], n_nodes)) # aggregate the edge messages around every node_**
For example, the i-th node should aggregate the edge around it, however, the code above maybe mean that the i-th code not only aggregates the edge around it, but also some other related or not related edge, which is not shown in the paper equation (4)
Firstly, tf.math.unsorted_segment_sum(messages, edges[:, 0], n_nodes) aggregate the edge feature around edges[:,0] indices.
Next, tf.math.unsorted_segment_sum(messages, edges[:, 1], n_nodes) aggregate the edge feature around edges[:,1] indices.
However, the two final features  2*[n_nodes, n_features] is about different indices. 
Did I make a mistake in my understanding?

**Comment by junfeng-chen** [comment]
Sorry for the late response. I did not realize this issue till today....
The output ***of tf.math.unsorted_segment_sum(messages, edges[:, 0], n_nodes)*** is a tensor with ***n_nodes*** rows. To compute its ***i***-th row, we sum such rows of ***messages***, that the corresponding rows of ***edges[:, 0]*** are exactly equal to ***i***. However, the node index ***i*** may falls to the second column of certain edges. So we do the similar aggregation conditioned on ***edges[:, 0]***, which leads to ***tf.math.unsorted_segment_sum(messages, edges[:, 1], n_nodes)***

I hope this explaination can help you. For reference of the fucntion ***tf.math.unsorted_segment_sum***: [https://www.tensorflow.org/api_docs/python/tf/math/unsorted_segment_sum](url)

**Comment by junfeng-chen** [comment]
/> In the [gnn_laminar_flow](https://github.com/cfl-minds/gnn_laminar_flow)/network_utils.py / Line 25: **_updates = tf.math.add(tf.math.unsorted_segment_sum(messages, edges[:, 0], n_nodes), tf.math.unsorted_segment_sum( messages, edges[:, 1], n_nodes)) # aggregate the edge messages around every node_** For example, the i-th node should aggregate the edge around it, however, the code above maybe mean that the i-th code not only aggregates the edge around it, but also some other related or not related edge, which is not shown in the paper equation (4) Firstly, tf.math.unsorted_segment_sum(messages, edges[:, 0], n_nodes) aggregate the edge feature around edges[:,0] indices. Next, tf.math.unsorted_segment_sum(messages, edges[:, 1], n_nodes) aggregate the edge feature around edges[:,1] indices. However, the two final features 2*[n_nodes, n_features] is about different indices. Did I make a mistake in my understanding?

Sorry for the late response. I did not realize an issue in this repository till today. Since more details are presented here than that on [https://github.com/cfl-minds/gnn_laminar_flow/issues/6](url), I think that I understand your concerns.

The output ***of tf.math.unsorted_segment_sum(messages, edges[:, 0], n_nodes)*** is a tensor with ***n_nodes*** rows. To compute its ***i***-th row, we sum such rows of ***messages***, that the corresponding rows of ***edges[:, 0]*** are exactly equal to ***i***. However, the node index ***i*** may falls to the second column of certain edges. So we do the similar aggregation conditioned on ***edges[:, 1]***, which leads to ***tf.math.unsorted_segment_sum(messages, edges[:, 1], n_nodes)***

I hope this explaination can help you. For reference of the fucntion ***tf.math.unsorted_segment_sum***: [https://www.tensorflow.org/api_docs/python/tf/math/unsorted_segment_sum](url)
